version: '2'
services:
    jhipstermojobs-app:
        image: jhipstermojobs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermojobs-mysql:3306/jhipstermojobs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermojobs-mysql:
        extends:
            file: mysql.yml
            service: jhipstermojobs-mysql
